### ISSUE TITLE
raspberry pico w

### ISSUE THREAD

**Issue by kazikaas** [dbisu/pico-ducky#106] opened 2022-10-01 16:30 UTC
does this work with the raspberry pico w, and if not do you already have a version for the raspberry pico w

**Comment by p-i-c-o** [comment] 2022-10-01 19:38
I have a feeling that the current code should work with the new chip

**Comment by dbisu** [comment] 2022-10-02 15:28
I'm still working on getting a pico w. I should have one soon.  I expect then it will take a couple of weeks to make the updates to support the wireless features.
I appears that CircuitPython 8.x will support the Pico W.

**Comment by lorelolorelo** [comment] 2022-10-20 14:25
I was playing with the code that you have available here,`https://github.com/dbisu/feathers2-ducky` it seems that adapting it is not very complicated even though I am not an expert.

In any case, it loads all the code except for the webpage, I've never deal with wsgi before, but it seems that some regex or similar is not right.

The only things I have changed is `wifi.radio.ipv4_address_ap` for `wifi.radio.ipv4_address`

And it seems AP mode is not available yet for circuit python so this line won't work... Sugestions are welcome in any case i plan to spend some more time on the wekeend :)

**Comment by dbisu** [comment] 2022-11-01 00:20
Closing, duplicate of #80 
I have a Pico W now, just need some time to get it working.

**Closed by dbisu** 2022-11-01 00:20 UTC
