### ISSUE TITLE
How to change keyboard language in italian?

### ISSUE THREAD

**Issue by sergio-delia** [dbisu/pico-ducky#20] opened 2021-09-19 14:39 UTC
I tried to edit code.py but it doesn't work.

**Comment by GamehunterKaan** [comment] 2021-09-19 15:14
Take A Look At [This](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts).

**Comment by dbisu** [comment] 2021-09-19 15:27
Closing as a duplicate of issue #10  Look at that issue for ways to handle non-US keyboards.

**Closed by dbisu** 2021-09-19 15:27 UTC
