### ISSUE TITLE
wait_for_button_press Command Not Working

### ISSUE THREAD

**Issue by PixellNerd** [dbisu/pico-ducky#114] opened 2022-11-15 20:49 UTC
When the script runs, it skips over any `wait_for_button_press` commands. I have tested my own scrips as well as the example scrips from the Rubber Ducky documentation (images below respectively)
![image_2022-11-15_154931997](https://user-images.githubusercontent.com/39127561/202022503-59105a75-7293-430d-928b-3676bf0c6d9e.png)
![image_2022-11-15_154945102](https://user-images.githubusercontent.com/39127561/202022533-da0414c5-1972-4dc7-822a-ebf1f78725fc.png)

As far as I can tell, there shouldn't be any button pressed down that would cause it to be skipped over.
Any help would be appreciated!

**Comment by dbisu** [comment] 2022-11-16 00:58
WAIT_FOR_BUTTON_PRESS is not currently implemented.  See issue #103

**Comment by dbisu** [comment] 2023-02-18 21:54
Closing as duplicate of #103

**Closed by dbisu** 2023-02-18 21:54 UTC
