### ISSUE TITLE
every thing working fine but payload is not executing

### ISSUE THREAD

**Issue by bharathdpv** [dbisu/pico-ducky#112] opened 2022-11-06 02:52 UTC
![image](https://user-images.githubusercontent.com/101401135/200151698-9fce0b48-77bd-403d-8718-396c7030a326.png)

see the payload is not working in my pc..

any solution??

**Comment by one-twoo** [comment] 2022-11-06 21:47
what's your payload.dd look like ?
what's your keyboard layout and did you added the necessary keyboard libraries ?
have you added a push button or payload selector to your pico ? and if you modified your board whats the situation of the modified pins?
do you have boot.py in the root of the pico?

**Comment by bharathdpv** [comment] 2022-11-11 11:46
ohhh so much question i will answer!!

my payload.dd look like:
![image](https://user-images.githubusercontent.com/101401135/201333531-7342fb73-b928-4a18-a495-b84880069bbf.png)

my keyboard layout:
![image](https://user-images.githubusercontent.com/101401135/201333769-defaf12c-f1cd-4c7b-952d-3b73345dcc49.png)

yes i added all the nessory library 
![image](https://user-images.githubusercontent.com/101401135/201333873-6c1fdfcc-d771-4e6b-9eaf-556ac7d1b0ff.png)

yes i have boot.py in my root !!

payload selector is in the code !!   no i did not modified any pins

**Comment by dbisu** [comment] 2022-11-11 15:51
I tested this payload on a pico board here and it worked for me(tm).
Try adding this line after line 168:
`print(line)`
and then capture the debug serial output.

**Comment by bharathdpv** [comment] 2022-11-12 02:19
![image](https://user-images.githubusercontent.com/101401135/201452029-46e62e6c-6d07-43ed-a62c-b66417e4d811.png)

NOTHING WORKS!!!

**Comment by dbisu** [comment] 2022-11-12 03:10
Have you tried blanking the pico and installing from the release v1.4 zip?
Also, did you modify other lines?  The code should go into a loop and not go to the `Code done running` statement without stopping the program.

**Comment by bharathdpv** [comment] 2022-11-12 03:18
Yes I modified the lines  because only the led up and down no other lines showing in the debug console so, I modified for my use and the code works fine but after few  time working it stoped working(I also changed the pc and Android phone even cable).

**Comment by dbisu** [comment] 2022-11-12 03:39
I am unable to reproduce this issue.
My recommendation would be to start over with the v1.4 image.

**Comment by bharathdpv** [comment] 2022-11-12 04:04
reinstalled  v1.4 same issue

https://user-images.githubusercontent.com/101401135/201456252-674d3357-0983-4199-b315-82268d786498.mp4

check out this video!!

**Comment by dbisu** [comment] 2022-11-12 04:09
If you unplug the device from your computer and plug it back in, does it run the payload?  This would be without using the IDE.

**Comment by bharathdpv** [comment] 2022-11-12 04:21
nah nothing works only the led blinking and the circuitpy window popping off!!

**Comment by dbisu** [comment] 2022-11-12 04:48
I am unfortunately unable to reproduce on the boards I have here.
From what you have shared, there are no errors running the code and it is able to find your payload.
If you run the step manually, do they work properly on you computer?

**Comment by bharathdpv** [comment] 2022-11-12 04:51
It works some time and it won't work, last week it works fine but now it's not working

**Comment by dbisu** [comment] 2022-11-12 05:14
I've not seen that issue.  Based on the information provided, I would expect it to be working.

**Comment by dbisu** [comment] 2023-02-18 21:36
Closing, not active.

**Closed by dbisu** 2023-02-18 21:36 UTC
