### ISSUE TITLE
does while work?

### ISSUE THREAD

**Issue by Aki99r** [dbisu/pico-ducky#229] opened 2024-01-29 14:04 UTC
quick question, does while work or is it even a thing  because when i check the rubber ducky documentation it exist but doesn't work for me when i write the payload.
Ty in advanced.

**Comment by dbisu** [comment] 2024-01-31 01:50
No, WHILE is part of DuckyScript 3.0 which is not supported at this time.

**Comment by dbisu** [comment] 2024-02-15 05:13
Closing, duplicate of #117

**Closed by dbisu** 2024-02-15 05:13 UTC
